# User config
author: "Femi Olukoya"
tagline: "Will code for food."
description: "Senior software engineer currently working Discord's financial platform. I've done full stack, ML infra, and money movement compliance"
keywords: "Software"
email: "femi.was.taken@gmail.com"
linkedin: "https://www.linkedin.com/aquafemi"

# Site config
baseurl: ""
url: "http://femi.xyz"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed