# User config
author: "Femi Olukoya"
tagline: "A summary of me."
description: "A software engineer experienced in backend ML infrastructure and full-stack development. I aspire to be at the intersection of unconstrained vision and sound architecture."
keywords: "Software"
email: "oolukoya96@gmail.com"
linkedin: "https://www.linkedin.com/oolukoya"

# Site config
baseurl: ""
url: "http://femi.xyz"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed