# Site settings
title: Under the C
email: oolukoya@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  A summary of me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aquafemi.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  aquafemi

# Build settings
markdown: kramdown
