# Site settings
title: Under the C
email: oolukoya96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A summary of me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://femi.xyz" # the base hostname & protocol for your site
twitter_username:
github_username:  aquafemi
linkedin_username: oolukoya

collections:
  blogs:
    permalink: /:collection/:name/
    output: true

# Build settings
markdown: kramdown
