# User config
author: "Femi Olukoya"
tagline: "A summary of me."
description: "Software engineer experienced in backend ML services and full-stack development - thriving at the intersection of vision and architecture."
keywords: "Software"
email: "oolukoya96@gmail.com"
linkedin: "https://www.linkedin.com/oolukoya"

# Site config
baseurl: ""
url: "http://femi.xyz"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed